import type { Metadata } from "next";
import Link from "next/link";
import { Reveal } from "@/components/reveal";

export const metadata: Metadata = {
  title: "Privacy",
  description:
    "Exactly what Summit does with your audio, what touches the network, and what it cannot do.",
};

const SECTIONS = [
  {
    heading: "What happens to your audio",
    paragraphs: [
      "Summit opens the file you selected, converts it with FFmpeg on your machine, and runs every model locally. The transcript, the speaker labels, the timestamps, and the meeting notes are all produced by software executing on your own hardware.",
      "No audio, transcript, or note text is sent to an API. There is no Summit account, no sync, no analytics call, and no server-side copy of anything, because there is no Summit server.",
    ],
  },
  {
    heading: "What touches the network",
    paragraphs: [
      "Model weights are downloaded the first time you use them. The Whisper and alignment models come from Hugging Face's public model hub. The pyannote speaker-diarization model is gated by its authors, so Summit authenticates with the read token you supply and downloads it into your normal local cache.",
      "After the models are on disk, you can disconnect the machine and Summit keeps working. If you later add a model or change one, that download needs the network again.",
    ],
  },
  {
    heading: "Your Hugging Face token",
    paragraphs: [
      "The token is stored in your operating system credential store, not in the settings file. It is filtered out of the application logs. You can also supply it through the HF_TOKEN environment variable instead of entering it in the interface.",
    ],
  },
  {
    heading: "Logs and settings",
    paragraphs: [
      "Summit keeps rotating local logs containing the application version, Python and PyTorch versions, GPU and VRAM information, which models were selected, how long each stage took, any fallback decisions, and exceptions. These files stay on your computer and exist so you can diagnose a slow or failed run.",
      "Non-secret settings live in %APPDATA%\\SpeakerTranscriber on Windows and ~/.config/speaker_transcriber on Linux. Deleting those directories resets the application.",
    ],
  },
  {
    heading: "Meeting notes",
    paragraphs: [
      "AI-written notes are generated by Ollama, which also runs on your machine. Summit sends the transcript to the local Ollama process over localhost and nowhere else. If you never install Ollama, the notes feature is simply unavailable and transcription is unaffected.",
    ],
  },
  {
    heading: "This website",
    paragraphs: [
      "The marketing site you are reading collects nothing beyond an email address, and only if you type one into the launch list form. There is no tracking pixel, no advertising script, and no cross-site profiling.",
    ],
  },
  {
    heading: "What Summit cannot do",
    paragraphs: [
      "Diarization answers who spoke when, by grouping similar voices into anonymous labels. It is not voice identification: Summit does not compare a voice against enrolled identities and cannot tell you a person's name on its own. You assign the names after processing.",
      "Accuracy is probabilistic. Similar voices, crosstalk, short interjections, music, reverberation, background noise, and telephone audio all reduce it. Overlapping turns and uncertainty are preserved in the JSON export rather than hidden, so you can see where the model was unsure.",
    ],
  },
];

export default function PrivacyPage()
{
  return (
    <div className="page-pad mx-auto w-full max-w-3xl py-16 sm:py-28">
      <Reveal>
        <p className="font-display text-xs font-semibold uppercase tracking-[0.22em] text-accent">
          Privacy
        </p>
        <h1 className="mt-4 font-display text-4xl font-bold leading-tight text-ink sm:text-5xl">
          Where your recordings go
        </h1>
        <p className="mt-5 text-lg leading-relaxed text-dim">
          Nowhere. That is the short version, and the rest of this page explains
          precisely why that claim holds.
        </p>
      </Reveal>

      <div className="mt-14 space-y-12">
        {SECTIONS.map((section, index) => (
          <Reveal key={section.heading} delay={index * 0.04}>
            <h2 className="font-display text-xl font-bold text-ink">
              {section.heading}
            </h2>
            {section.paragraphs.map((paragraph) => (
              <p key={paragraph} className="mt-3 text-sm leading-relaxed text-muted">
                {paragraph}
              </p>
            ))}
          </Reveal>
        ))}
      </div>

      <Reveal delay={0.2}>
        <div className="mt-16 rounded-panel border border-edge bg-surface p-6 text-center">
          <p className="text-sm text-dim">
            Still have a question your security team needs answered?
          </p>
          <Link
            href="/#waitlist"
            className="mt-3 inline-flex text-sm font-medium text-accent transition-colors hover:text-accent-hover"
          >
            Get in touch &rarr;
          </Link>
        </div>
      </Reveal>
    </div>
  );
}
